'''Simple XML property list library that is based on 'xml.etree.ElementTree'.

XML property list is a property list based on XML format. Plist keys and
values are being described as individual XML tags. Plist XML tags are being
defined in `DEFAULT_KEY_IDS` global variable that can be updated using the
`updatekeys` method. Different tags can be associated with the same Plist object
and therefore `DEFAULT_KEY_IDS` contains a list of aliases. The first tag in the
list is used when constructing Plist objects inside methods that cannot be
controlled by the user; such functions include `__setitem__` and `__getitem__`
inside `PlistElement` class and `fromdict` method.

`PlistElement` is a container that can contain multiple sub-nodes if it is a
directory object. When initializing non-directory Plist objects, a inner text is
needed, an exception is 'NSBool' objects.

Accessing and overwriting sub-nodes in directory objects is done using [] key
operator. Appending new objects in a 'NSArray' is done using
`PlistElement.append` method. When trying to set a object in a 'NSDictionary',
by a non-defined key, it creates a new key and links the value to it. Removing
a object in both 'NSDictionary' and 'NSArray' is done using `PlistElement.pop`
method. In 'NSDictionary' both the key and the linked value are being removed.

Multiple methods can be used to build a property list tree from a source. Such
methods include `fromdict`, `fromfile` and `fromstring` methods. This module
also contains methods to convert an already existing `PlistElement` tree into a
string or dict.

Notes
-----
    (1) When parsing a string or a file that uses non-standart Plist tag
    definitions, you need to update the current tag namespace using `updatekeys`
    method.

    (2) `PlistElement.pop` works for both 'NSArray' and 'NSDictionary', but does
    not return the removed element in the same way as `dict.pop` and `list.pop`
    methods do.

    (3) Converting a property list tree into a dict using `todict` method, does
    not copy inner-tag attributes from `PlistElement` object to the dict.


'''

#       [1]    License                                                         #
# -----------------------------------------------------------------------------+
# Boost Software License - Version 1.0 - August 17th, 2003                     |
#                                                                              |
# Permission is hereby granted, free of charge, to any person or organization  |
# obtaining a copy of the software and accompanying documentation covered by   |
# this license (the "Software") to use, reproduce, display, distribute,        |
# execute, and transmit the Software, and to prepare derivative works of the   |
# Software, and to permit third-parties to whom the Software is furnished to   |
# do so, all subject to the following:                                         |
#                                                                              |
# The copyright notices in the Software and this entire statement, including   |
# the above license grant, this restriction and the following disclaimer,      |
# must be included in all copies of the Software, in whole or in part, and     |
# all derivative works of the Software, unless such copies or derivative       |
# works are solely in the form of machine-executable object code generated by  |
# a source language processor.                                                 |
#                                                                              |
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR   |
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,     |
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT    |
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE    |
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,  |
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER  |
# DEALINGS IN THE SOFTWARE.                                                    |
#                                                                              |
#                                                                              |
# ******************************************************************************

#       [2]     Credits                                                        #
# -----------------------------------------------------------------------------+                                                              |
# This software extends, uses and copies methods from the 'ElementTree'        |
# toolkit. The full credit goes to Fredrik Lundh and Secret Labs AB.           |
# Their copyright terms can be seen bellow.                                    |
#                                                                              |
# []:   The ElementTree toolkit is                                             |
# []:                                                                          |
# []:   Copyright (c) 1999-2008 by Fredrik Lundh                               |
# []:                                                                          |
# []:   fredrik@pythonware.com                                                 |
# []:   http://www.pythonware.com                                              |
# []:                                                                          |
# []:                                                                          |
# []:   By obtaining, using, and/or copying this software and/or its           |
# []:   associated documentation, you agree that you have read, understood,    |
# []:   and will comply with the following terms and conditions:               |
# []:                                                                          |
# []:   Permission to use, copy, modify, and distribute this software and      |
# []:   its associated documentation for any purpose and without fee is        |
# []:   hereby granted, provided that the above copyright notice appears in    |
# []:   all copies, and that both that copyright notice and this permission    |
# []:   notice appear in supporting documentation, and that the name of        |
# []:   Secret Labs AB or the author not be used in advertising or publicity   |
# []:   pertaining to distribution of the software without specific, written   |
# []:   prior permission.                                                      |
# []:                                                                          |
# []:   SECRET LABS AB AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD     |
# []:   TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANT-        |
# []:   ABILITY AND FITNESS.  IN NO EVENT SHALL SECRET LABS AB OR THE AUTHOR   |
# []:   BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY    |
# []:   DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,        |
# []:   WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS         |
# []:   ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE    |
# []:   OF THIS SOFTWARE.                                                      |
#                                                                              |
#                                                                              |
# ******************************************************************************
from typing import Union
from datetime import date, datetime


VERSION = '0.0.1'

# Allowed-Plist-Types
APTypes = Union[int, float, str, bytes, bytearray, date, datetime]